### ISSUE TITLE
按需（懒）加载（vue实现），其实是Webpack4的动态导入

### ISSUE THREAD

**Issue by luoway** [wangyupo/vue-vuex-router#1]
文件：[src/router/index.js](https://github.com/wangyupo/vue-vuex-router/blob/2cfe6abab91d6e1b87d82f4a2c7f3eac23015046/src/router/index.js)

代码段：
```js
// 正常加载
// import Home from '../views/home'
// import About from '../views/About'

// 按需（懒）加载（vue实现）
const Home = () => import( /* webpackChunkName: "home" */ '../views/home')
const About = () => import( /* webpackChunkName: "about" */ '../views/about')

// 按需（懒）加载（webpack实现）
// const Home = r => require.ensure([], () => r(require('../views/home')), 'home')
// const About = r => require.ensure([], () => r(require('../views/About')), 'about')
```

参考文档：

[Webpack 动态导入](https://webpack.docschina.org/guides/code-splitting#%E5%8A%A8%E6%80%81%E5%AF%BC%E5%85%A5-dynamic-imports-)

[require.ensure](https://webpack.docschina.org/api/module-methods/#require-ensure)

> require.ensure() 是 webpack 特有的，已经被 import() 取代。

**Comment by wangyupo** [comment]
谢谢，已修正。已做为新手参考使用，防止看到类似代码不知道其作用。
