### ISSUE TITLE
amfe-flexible的疑问

### ISSUE THREAD

**Issue by Basakerone** [wangyupo/vue-vuex-router#2]
作者你好，我是一个新手，amfe-flexible貌似推荐用vw的兼容方案，请问有意向要替换一下适配的方式吗?

**Comment by wangyupo** [comment]
首先，用这个脚手架，在公司要求时间内完成任务是一件十分简单而快乐的事情。vw适配，实际上和这个一样，等我开个分支给你写一个。有什么要求尽管提issues，欢迎入群探讨。

**Comment by Basakerone** [comment]
谢谢作者回答。期待vm方式。
