### ISSUE TITLE
store 问题

### ISSUE THREAD

**Issue by newlifebegins** [wangyupo/vue-vuex-router#5]
我在getter中取数据的时候，有时候action中的方法还没有执行完成，这个您是怎么解决的了

**Comment by wangyupo** [comment]
getter不是放在computed中会监听数据变动吗？等他完成了不就有值了吗？

**Comment by wangyupo** [comment]
> 我在getter中取数据的时候，有时候action中的方法还没有执行完成，这个您是怎么解决的了

getter不是放在computed中会监听数据变动吗？等他完成了不就有值了吗？
