### ISSUE TITLE
用您的这个 跑起来了，但是 出现 CORS 跨域问题

### ISSUE THREAD

**Issue by gamegg** [wangyupo/vue-vuex-router#7]
您好，请问用您的这个 跑起来了，但是 出现 CORS 跨域问题

Access to XMLHttpRequest at 'http://api.zhuishushenqi.com/ranking/gender' from origin 'http://192.168.0.10:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
user.js?6a9f:28 Error: Network Error
    at createError (createError.js?2d83:16)
    at XMLHttpRequest.handleError (xhr.js?b50d:84)

请问该如何解决呢？ 感谢

**Comment by wangyupo** [comment]
如果你有具体业务，并且有测试环境，就让负责后端的同事帮你解决。如果是本地调试，参考文档：https://cli.vuejs.org/zh/config/#devserver
